[constants]
app_pi = 3.14
app_name = "MyApp"

[general]
name = "#(app_name)"
version = 1

[database]
host = "localhost"
port = 5432

[logging]
level = "info"

[math]
circle_area = "#(app_pi)"
